"""SpaceLoop Backend ORM Models (delegating to backend.app.persistence.models).

Guarantees a SINGLE authoritative source of truth for all SQLAlchemy ORM models,
table metadata, relationships, and persistence mappings across the entire application.
"""
from backend.app.persistence.models import (
    AccessLog,
    AuditLog,
    Booking,
    DeviceSession,
    EmailLog,
    EmailVerificationToken,
    EscrowLedger,
    EscrowTransaction,
    FraudAlert,
    FraudAlertRecord,
    FraudEvent,
    FraudEventRecord,
    MFARecoveryCode,
    Notification,
    PasswordResetToken,
    Review,
    RiskAssessment,
    Space,
    SpaceInquiry,
    User,
    db,
    utc_now,
)

__all__ = [
    "db",
    "utc_now",
    "User",
    "Space",
    "Booking",
    "EscrowLedger",
    "EscrowTransaction",
    "AccessLog",
    "Review",
    "SpaceInquiry",
    "Notification",
    "DeviceSession",
    "PasswordResetToken",
    "EmailVerificationToken",
    "MFARecoveryCode",
    "AuditLog",
    "EmailLog",
    "FraudAlert",
    "FraudAlertRecord",
    "FraudEvent",
    "FraudEventRecord",
    "RiskAssessment",
]
