export const SPACES_DATA = [
  {
    id: '1',
    title: 'The Glass Loft Pavilion & Rooftop',
    category: 'Coworking & Lounge',
    location: 'Design District, San Francisco',
    price: 35,
    rating: 4.95,
    reviews: 84,
    capacity: 18,
    instantAccess: true,
    image: '/images/hero-light.jpeg',
    description: 'A stunning multi-level architectural pavilion with warm cedar finishes, floor-to-ceiling glass panoramic windows, and open-air rooftop garden workspace.',
    amenities: ['High-speed 1Gbps WiFi', 'Smart Keyless Access', 'Espresso Bar', 'Ergonomic Herman Miller Chairs', 'Conference Display', 'Rooftop Lounge'],
  },
  {
    id: '2',
    title: 'The Atrium Sunlit Studio',
    category: 'Creative Studio',
    location: 'SoHo Arts District, New York',
    price: 45,
    rating: 4.92,
    reviews: 62,
    capacity: 12,
    instantAccess: true,
    image: '/images/hero-dark.jpeg',
    description: 'High ceiling architectural space with diffused natural skylights, acoustic wood paneling, and motorized standing desks.',
    amenities: ['Natural Light Skylights', 'Smart Access Pass', 'Podcast Audio Setup', 'Whiteboards', 'Tea & Coffee Station'],
  },
  {
    id: '3',
    title: 'Timber Vault Boardroom',
    category: 'Conference Room',
    location: 'Downtown Financial Quarter, Chicago',
    price: 60,
    rating: 4.88,
    reviews: 41,
    capacity: 16,
    instantAccess: false,
    image: '/images/hero-light.jpeg',
    description: 'Quiet executive meeting suite with warm architectural illumination, dual 75" 4K displays, and secure soundproofing.',
    amenities: ['Dual 4K Displays', 'Zoom Rooms System', 'Secure Soundproofing', 'Private Restroom', 'Catering Station'],
  },
  {
    id: '4',
    title: 'Rooftop Canopy Workspace',
    category: 'Outdoor & Lounge',
    location: 'South Beach, Miami',
    price: 28,
    rating: 4.97,
    reviews: 110,
    capacity: 25,
    instantAccess: true,
    image: '/images/hero-dark.jpeg',
    description: 'Open-air terrace equipped with weather-proof power pods, shaded teak cabanas, and panoramic sunset skyline views.',
    amenities: ['Power Outlets at Every Desk', 'Shaded Cabanas', 'Sunset Horizon View', 'High-Speed Mesh WiFi', 'Refreshment Bar'],
  },
  {
    id: '5',
    title: 'Nordic Minimalist Focus Pods',
    category: 'Private Office',
    location: 'Pioneer Square, Seattle',
    price: 30,
    rating: 4.85,
    reviews: 35,
    capacity: 6,
    instantAccess: true,
    image: '/images/hero-light.jpeg',
    description: 'Distraction-free acoustic pods built with pale birch wood and warm ambient lighting. Perfect for deep sprints.',
    amenities: ['Acoustic Isolation', 'Focus Lighting Controls', 'Air Quality Monitoring', 'Smart Passcode Lock'],
  },
  {
    id: '6',
    title: 'The Gallery Open Floor',
    category: 'Event & Workshop',
    location: 'Arts Quarter, Austin',
    price: 85,
    rating: 4.91,
    reviews: 73,
    capacity: 40,
    instantAccess: false,
    image: '/images/hero-dark.jpeg',
    description: 'Spacious gallery venue with modular moveable furniture, high industrial ceilings, and architectural track spotlighting.',
    amenities: ['Modular Furniture', '4K Laser Projector', 'Surround Sound', 'Kitchenette', 'Wheelchair Accessible'],
  },
];
